-- Create a yearly leaderboard view (present count per member per YYYY)
-- Generated by tooling to mirror monthly_leaderboard but aggregated per year.

CREATE VIEW public.yearly_leaderboard AS
SELECT
  to_char(s.date, 'YYYY')  AS year,
  m.id                      AS member_id,
  m.full_name,
  m.team,
  m.offline_code,
  COUNT(*)                  AS present_count
FROM public.clock_ins ci
JOIN public.members  m ON m.id = ci.member_id
JOIN public.sessions s ON s.id = ci.session_id
WHERE ci.status = 'present'
GROUP BY to_char(s.date, 'YYYY'), m.id, m.full_name, m.team, m.offline_code;

-- End of migration
